rsna
[RSNADataset] Scanning files...
[RSNADataset] Found 1000 already processed bags
[RSNADataset] Number of bags found: 1000
rsna
[RSNADataset] Scanning files...
[RSNADataset] Found 150 already processed bags
[RSNADataset] Number of bags found: 150
Traceback (most recent call last):
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_main.py", line 54, in <module>
    trainer.train()
  File "/home/javitrucas/TFG/scripts/medical_scripts/medical_training.py", line 27, in train
    output = model(bag_data)
             ^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/TFG/scripts/model.py", line 64, in forward
    instances = bag_data.view(batch_size * max_bag_size, 1, 28, 28)  # (batch_size * max_bag_size, 1, 28, 28)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[40, 1, 28, 28]' is invalid for input of size 20480
