2025-03-04 11:26:26,791 INFO    MainThread:631750 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 11:26:26,791 INFO    MainThread:631750 [wandb_setup.py:_flush():67] Configure stats pid to 631750
2025-03-04 11:26:26,791 INFO    MainThread:631750 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/.config/wandb/settings
2025-03-04 11:26:26,791 INFO    MainThread:631750 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/TFG/wandb/settings
2025-03-04 11:26:26,791 INFO    MainThread:631750 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 11:26:26,791 INFO    MainThread:631750 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/wandb/run-20250304_112626-fobyyrr4/logs/debug.log
2025-03-04 11:26:26,792 INFO    MainThread:631750 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/wandb/run-20250304_112626-fobyyrr4/logs/debug-internal.log
2025-03-04 11:26:26,792 INFO    MainThread:631750 [wandb_init.py:init():761] calling init triggers
2025-03-04 11:26:26,792 INFO    MainThread:631750 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 1, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-03-04 11:26:26,792 INFO    MainThread:631750 [wandb_init.py:init():784] starting backend
2025-03-04 11:26:26,792 INFO    MainThread:631750 [wandb_init.py:init():788] sending inform_init request
2025-03-04 11:26:26,796 INFO    MainThread:631750 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-04 11:26:26,797 INFO    MainThread:631750 [wandb_init.py:init():803] backend started and connected
2025-03-04 11:26:26,799 INFO    MainThread:631750 [wandb_init.py:init():896] updated telemetry
2025-03-04 11:26:26,809 INFO    MainThread:631750 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 11:26:27,206 INFO    MainThread:631750 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 11:26:27,351 INFO    MainThread:631750 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 11:26:27,352 INFO    MainThread:631750 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 11:26:27,352 INFO    MainThread:631750 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 11:26:27,352 INFO    MainThread:631750 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 11:26:27,356 INFO    MainThread:631750 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 11:26:48,769 INFO    MainThread:631750 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-04 11:26:49,958 WARNING MsgRouterThr:631750 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-04 11:26:49,960 INFO    MsgRouterThr:631750 [mailbox.py:close():115] Closing mailbox, abandoning 2 handles.
