2025-03-14 09:44:06,136 INFO    MainThread:3892445 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-14 09:44:06,136 INFO    MainThread:3892445 [wandb_setup.py:_flush():67] Configure stats pid to 3892445
2025-03-14 09:44:06,136 INFO    MainThread:3892445 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/.config/wandb/settings
2025-03-14 09:44:06,136 INFO    MainThread:3892445 [wandb_setup.py:_flush():67] Loading settings from /home/javitrucas/TFG/notebooks/wandb/settings
2025-03-14 09:44:06,136 INFO    MainThread:3892445 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094406-uoo0bly4/logs/debug.log
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094406-uoo0bly4/logs/debug-internal.log
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6b0754e790>
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:init():761] calling init triggers
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'panda-patches_512_preset-features_UNI', 'input_feature_dim': 1024, 'feature_dim': 128, 'num_epochs': 10, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:init():784] starting backend
2025-03-14 09:44:06,137 INFO    MainThread:3892445 [wandb_init.py:init():788] sending inform_init request
2025-03-14 09:44:06,141 INFO    MainThread:3892445 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-14 09:44:06,142 INFO    MainThread:3892445 [wandb_init.py:init():803] backend started and connected
2025-03-14 09:44:06,145 INFO    MainThread:3892445 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-14 09:44:06,371 INFO    MainThread:3892445 [wandb_init.py:init():896] updated telemetry
2025-03-14 09:44:06,381 INFO    MainThread:3892445 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-14 09:44:06,636 INFO    MainThread:3892445 [wandb_init.py:init():995] starting run threads in backend
2025-03-14 09:44:06,828 INFO    MainThread:3892445 [wandb_run.py:_console_start():2377] atexit reg
2025-03-14 09:44:06,828 INFO    MainThread:3892445 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-14 09:44:06,828 INFO    MainThread:3892445 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-14 09:44:06,829 INFO    MainThread:3892445 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-14 09:44:06,832 INFO    MainThread:3892445 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-14 09:45:24,149 INFO    MainThread:3892445 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:45:24,150 INFO    MainThread:3892445 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 09:48:14,327 INFO    MainThread:3892445 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 09:48:14,395 INFO    MainThread:3892445 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:48:14,396 INFO    MainThread:3892445 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 09:48:23,641 INFO    MainThread:3892445 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 09:48:23,681 INFO    MainThread:3892445 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:48:23,682 INFO    MainThread:3892445 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 09:49:52,154 INFO    MainThread:3892445 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 09:49:52,163 INFO    MainThread:3892445 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094952-tqdvjt8q/logs/debug.log
2025-03-14 09:49:52,163 INFO    MainThread:3892445 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_094952-tqdvjt8q/logs/debug-internal.log
2025-03-14 09:49:52,163 INFO    MainThread:3892445 [wandb_init.py:init():761] calling init triggers
2025-03-14 09:49:52,164 INFO    MainThread:3892445 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 50, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-03-14 09:49:52,164 INFO    MainThread:3892445 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 09:49:58,579 WARNING MsgRouterThr:3892445 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/javitrucas/miniconda3/envs/tfg/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-14 09:49:58,609 INFO    MsgRouterThr:3892445 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
2025-03-14 09:50:02,197 INFO    MainThread:3892445 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:50:02,198 INFO    MainThread:3892445 [wandb_init.py:_pause_backend():564] pausing backend
2025-03-14 09:50:03,814 INFO    MainThread:3892445 [wandb_init.py:_resume_backend():569] resuming backend
2025-03-14 09:50:04,451 INFO    MainThread:3892445 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_095004-3bn3xt1m/logs/debug.log
2025-03-14 09:50:04,451 INFO    MainThread:3892445 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/javitrucas/TFG/notebooks/wandb/run-20250314_095004-3bn3xt1m/logs/debug-internal.log
2025-03-14 09:50:04,451 INFO    MainThread:3892445 [wandb_init.py:init():761] calling init triggers
2025-03-14 09:50:04,452 INFO    MainThread:3892445 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'dataset_name': 'rsna-features_resnet18', 'num_epochs': 5, 'learning_rate': 0.001, 'batch_size': 1, 'val_prop': 0.2, 'seed': 42, 'use_inst_distances': False, 'adj_mat_mode': 'relative', '_wandb': {}}
2025-03-14 09:50:04,452 INFO    MainThread:3892445 [wandb_init.py:init():776] wandb.init() called while a run is active
2025-03-14 09:50:26,406 INFO    MainThread:3892445 [wandb_run.py:_config_callback():1261] config_cb ('_wandb', 'visualize', 'val_confusion_matrix') {'panel_type': 'Vega2', 'panel_config': {'panelDefId': 'wandb/confusion_matrix/v1', 'fieldSettings': {'Actual': 'Actual', 'Predicted': 'Predicted', 'nPredictions': 'nPredictions'}, 'stringSettings': {'title': 'Confusion Matrix Curve'}, 'transform': {'name': 'tableWithLeafColNames'}, 'userQuery': {'queryFields': [{'name': 'runSets', 'args': [{'name': 'runSets', 'value': '${runSets}'}], 'fields': [{'name': 'id', 'fields': []}, {'name': 'name', 'fields': []}, {'name': '_defaultColorIndex', 'fields': []}, {'name': 'summaryTable', 'args': [{'name': 'tableKey', 'value': 'val_confusion_matrix_table'}], 'fields': []}]}]}}} None
2025-03-14 09:50:27,395 INFO    MainThread:3892445 [jupyter.py:save_ipynb():386] not saving jupyter notebook
2025-03-14 09:50:27,396 INFO    MainThread:3892445 [wandb_init.py:_pause_backend():564] pausing backend
